(10)=
# Chapter 10: Basic Array Methods

**Topics Covered:**
- Creating and inspecting NumPy arrays
- Indexing and slicing (1D and 2D)
- Element-wise operations and broadcasting
- Reshaping and combining arrays
- Practical chemical engineering examples

> **Instructor Note:** Open by asking: "In the last few chapters, we've been using `np.linspace` and `np.exp` in our plotting code — but what actually *are* those things?" This chapter formally teaches the tool they've been using informally. Emphasize that NumPy is not optional — it's the foundation for everything coming next (linear algebra in Ch 11, curve fitting in Ch 13, ODEs later). Budget: ~15 min for 10.1, ~15 min for 10.2, ~15 min for 10.3, ~10 min for 10.4, ~10 min for 10.5.

(10.1)=
## 10.1 Introduction to NumPy Arrays

**NumPy** (Numerical Python) is the core library for scientific computing in Python. At its heart is the **ndarray** — a fast, memory-efficient array that supports vectorized operations.

Why use NumPy instead of Python lists?

| Feature | Python List | NumPy Array |
|---------|------------|-------------|
| Speed | Slow (interpreted loops) | Fast (compiled C under the hood) |
| Operations | Element-by-element with loops | Vectorized — operates on entire arrays at once |
| Math support | Manual implementation | Built-in: `sin`, `exp`, `mean`, `dot`, etc. |

In chemical engineering, we constantly work with large datasets — temperature profiles, concentration measurements, pressure readings — and NumPy makes processing them efficient.

> **Instructor Note:** Walk through the comparison table. The speed point is the most important — say: "A for-loop over a million data points might take seconds with a list. NumPy does it in milliseconds because the heavy lifting runs in compiled C, not interpreted Python." Don't dwell on memory — just mention it. The key takeaway for students: "If you're doing math on collections of numbers, use arrays, not lists."

(10.1.1)=
### 10.1.1 Creating Arrays

NumPy provides several built-in functions to create arrays:

| Function | Description | Example |
|----------|-------------|---------|
| `np.array(list)` | Create from a Python list | `np.array([1, 2, 3])` |
| `np.zeros(n)` | Array of `n` zeros | `np.zeros(5)` → `[0. 0. 0. 0. 0.]` |
| `np.ones(n)` | Array of `n` ones | `np.ones(4)` → `[1. 1. 1. 1.]` |
| `np.linspace(a, b, n)` | `n` evenly spaced points from `a` to `b` (inclusive) | `np.linspace(0, 1, 5)` → `[0. 0.25 0.5 0.75 1.]` |
| `np.arange(a, b, step)` | Values from `a` to `b` (exclusive) with `step` | `np.arange(0, 5, 0.5)` → `[0. 0.5 1. ... 4.5]` |
| `np.eye(n)` | `n×n` identity matrix | `np.eye(3)` → 3×3 with 1s on diagonal |
| `np.random.rand(n)` | `n` random values in [0, 1) | `np.random.rand(4)` → `[0.23 0.71 ...]` |
| `np.full(n, val)` | Array of `n` copies of `val` | `np.full(3, 7.5)` → `[7.5 7.5 7.5]` |

> **Instructor Note:** Don't try to cover all 8 at equal depth. Focus on the top 4 they'll use daily: `np.array`, `np.zeros`, `np.linspace`, `np.arange`. Run each cell one by one. For `linspace` vs `arange`, highlight the key difference: "linspace you specify *how many points*, arange you specify the *step size*. linspace includes the endpoint, arange does not." Ask: "If I want 100 points between 0 and 10 for a smooth plot, which one?" (linspace). "If I want every 0.1 seconds?" (arange). Briefly demo `np.full`, `np.eye`, and `np.random.rand` in the last cell — mention `np.eye` will come back in Chapter 11 for identity matrices.

In [2]:
import numpy as np

# From a Python list
temperatures = np.array([300, 350, 400, 450, 500])
print("From list:", temperatures)

From list: [300 350 400 450 500]


In [2]:
# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

Zeros: [0. 0. 0. 0. 0.]


In [3]:
# Array of ones
ones = np.ones(4)
print("Ones:", ones)

Ones: [1. 1. 1. 1.]


In [4]:
# Evenly spaced values (start, stop, num_points)
pressures = np.linspace(1, 10, 5)
print("Linspace:", pressures)

Linspace: [ 1.    3.25  5.5   7.75 10.  ]


In [5]:
# Evenly spaced values with step size (start, stop_exclusive, step)
time = np.arange(0, 5, 0.5)
print("Arange:", time)

Arange: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
# Array filled with a specific value
initial_conc = np.full(6, 2.5)  # 6 reactors all starting at 2.5 mol/L
print("Full:", initial_conc)

# Identity matrix (1s on diagonal, 0s elsewhere)
I = np.eye(3)
print("Identity:\n", I)

# Random values between 0 and 1
noise = np.random.rand(5)
print("Random:", noise)

(10.1.2)=
### 10.1.2 Arrays vs. Lists

A common mistake is to assume NumPy arrays behave like Python lists. They don't — and the difference matters.

> **Instructor Note:** This is one of the most important cells in the chapter. Run the list cell first, then the array cell, and let students see the difference side by side. Say: "With lists, `+` glues them together. With arrays, `+` does math." Then run the two demo cells below — the first shows that `np.exp(-0.3 * time)` works perfectly on an array, and the second shows that the same operation on a list crashes with `TypeError`. Let the error appear. Ask: "Why does this fail?" (because Python doesn't know how to multiply a list by a float — that's a NumPy operation). This is the single best demonstration of why arrays exist.

In [6]:
# List: + concatenates
py_list = [1, 2, 3]
print("List + List:", py_list + py_list)       # [1, 2, 3, 1, 2, 3]
print("List * 2:  ", py_list * 2)   # [1, 2, 3, 1, 2, 3]

List + List: [1, 2, 3, 1, 2, 3]
List * 2:   [1, 2, 3, 1, 2, 3]


In [7]:
# Array: + adds element-wise
np_array = np.array([1, 2, 3])
print("Array + Array:", np_array + np_array)   # [2, 4, 6]
print("Array * 2:   ", np_array * 2)           # [2, 4, 6]

Array + Array: [2 4 6]
Array * 2:    [2 4 6]


In [3]:
time = np.linspace(0, 10, 100)  # 100 points from 0 to 10

concentration = 5.0 * np.exp(-0.3 * time)  # First-order decay
print("Concentration as array:", concentration)

Concentration as array: [5.         4.85075752 4.7059697  4.56550358 4.42923016 4.2970243
 4.16876459 4.04433324 3.92361597 3.80650193 3.69288357 3.58265655
 3.47571964 3.37197464 3.27132626 3.17368209 3.07895246 2.98705036
 2.89789139 2.81139369 2.72747782 2.64606671 2.5670856  2.49046195
 2.41612541 2.3440077  2.27404259 2.20616584 2.14031511 2.07642992
 2.01445161 1.95432326 1.89598965 1.83939721 1.78449397 1.7312295
 1.67955491 1.62942272 1.5807869  1.53360279 1.48782705 1.44341765
 1.4003338  1.35853595 1.31798569 1.2786458  1.24048015 1.20345368
 1.1675324  1.13268331 1.09887442 1.06607467 1.03425394 1.00338302
 0.97343354 0.94437801 0.91618975 0.88884286 0.86231224 0.83657352
 0.81160306 0.78737793 0.76387588 0.74107533 0.71895535 0.69749561
 0.67667642 0.65647864 0.63688374 0.61787372 0.59943112 0.581539
 0.56418094 0.54734098 0.53100368 0.51515402 0.49977744 0.48485984
 0.4703875  0.45634714 0.44272587 0.42951117 0.4166909  0.40425331
 0.39218695 0.38048076 0.36912398 0.358106

In [12]:
time_list = list(time)
print("Time as list:", time_list)
concentration_list = 5.0 * np.exp(-0.3 * time_list) 

Time as list: [0.0, 0.1010101, 0.2020202, 0.3030303, 0.4040404, 0.50505051, 0.60606061, 0.70707071, 0.80808081, 0.90909091, 1.01010101, 1.11111111, 1.21212121, 1.31313131, 1.41414141, 1.51515152, 1.61616162, 1.71717172, 1.81818182, 1.91919192, 2.02020202, 2.12121212, 2.22222222, 2.32323232, 2.42424242, 2.52525253, 2.62626263, 2.72727273, 2.82828283, 2.92929293, 3.03030303, 3.13131313, 3.23232323, 3.33333333, 3.43434343, 3.53535354, 3.63636364, 3.73737374, 3.83838384, 3.93939394, 4.04040404, 4.14141414, 4.24242424, 4.34343434, 4.44444444, 4.54545455, 4.64646465, 4.74747475, 4.84848485, 4.94949495, 5.05050505, 5.15151515, 5.25252525, 5.35353535, 5.45454545, 5.55555556, 5.65656566, 5.75757576, 5.85858586, 5.95959596, 6.06060606, 6.16161616, 6.26262626, 6.36363636, 6.46464646, 6.56565657, 6.66666667, 6.76767677, 6.86868687, 6.96969697, 7.07070707, 7.17171717, 7.27272727, 7.37373737, 7.47474747, 7.57575758, 7.67676768, 7.77777778, 7.87878788, 7.97979798, 8.08080808, 8.18181818, 8.28282828, 

TypeError: can't multiply sequence by non-int of type 'float'

(10.2)=
## 10.2 Array Properties & Indexing

> **Instructor Note:** Transition: "Now that we can create arrays, let's learn how to inspect them and pull out specific values." This section connects directly to what they already know about list indexing — but extends it to 2D. If students look comfortable with 1D indexing, move quickly to 2D since that's the new material.

(10.2.1)=
### 10.2.1 Array Properties

Every NumPy array has attributes that describe its structure:

> **Instructor Note:** Run the 1D cell first. Point out that `.shape` returns a tuple — `(5,)` means "5 elements, 1 dimension." The trailing comma matters; it's Python's way of saying "this is a 1-element tuple." Then run the 2D cell. Emphasize `.shape` → `(4, 3)` means "4 rows, 3 columns" — this is the convention throughout: **(rows, columns)**. Ask: "What would `.shape` be for a 3×5 matrix?" Make sure students understand `.dtype` — `float64` is the default for decimals, `int64` for integers. They don't need to memorize dtypes, just know they exist.

In [13]:
# 1D array
temps = np.array([300.0, 350.0, 400.0, 450.0, 500.0])

print("Array:     ", temps)
print("Shape:     ", temps.shape)    # (5,) — 1D with 5 elements
print("Size:      ", temps.size)     # 5 total elements
print("Dimensions:", temps.ndim)     # 1
print("Data type: ", temps.dtype)    # float64

Array:      [300. 350. 400. 450. 500.]
Shape:      (5,)
Size:       5
Dimensions: 1
Data type:  float64


In [14]:
# 2D array (matrix)
data = np.array([
    [300, 1.5, 0.92],
    [350, 2.1, 0.85],
    [400, 3.0, 0.78],
    [450, 4.2, 0.70]
])

print("Array:\n", data)
print("Shape:     ", data.shape)    # (4, 3) — 4 rows, 3 columns
print("Size:      ", data.size)     # 12 total elements
print("Dimensions:", data.ndim)     # 2

Array:
 [[300.     1.5    0.92]
 [350.     2.1    0.85]
 [400.     3.     0.78]
 [450.     4.2    0.7 ]]
Shape:      (4, 3)
Size:       12
Dimensions: 2


(10.2.2)=
### 10.2.2 Indexing and Slicing — 1D Arrays

NumPy indexing works like Python list indexing (0-based), but with additional power for multi-dimensional arrays.

> **Instructor Note:** This should be quick review — they learned list indexing in Chapter 1. Run the cell and briefly confirm they remember: `[0]` is first, `[-1]` is last, `[1:3]` is elements 1 and 2 (stop is exclusive), `[::2]` is every other. If they're comfortable, spend less than 2 minutes here and move to 2D.

In [15]:
temps = np.array([300, 350, 400, 450, 500])

print("First element:  ", temps[0])      # 300
print("Last element:   ", temps[-1])     # 500
print("Slice [1:3]:    ", temps[1:3])    # [350, 400]
print("Every other:    ", temps[::2])    # [300, 400, 500]
print("Reversed:       ", temps[::-1])   # [500, 450, 400, 350, 300]

First element:   300
Last element:    500
Slice [1:3]:     [350 400]
Every other:     [300 400 500]
Reversed:        [500 450 400 350 300]


(10.2.3)=
### 10.2.3 Indexing and Slicing — 2D Arrays

For 2D arrays, use `[row, column]` syntax. This is different from nested list indexing (`list[row][col]`).

> **Instructor Note:** This is the key new concept. Draw a small grid on the board with row/column labels to visualize the data. Walk through each line in the code cell:
> - `data[1, 2]` → "row 1, column 2 — that's 0.85, the conversion from the second experiment"
> - `data[0, :]` → "row 0, all columns — the colon means 'everything'"
> - `data[:, 1]` → "all rows, column 1 — this pulls out the entire pressure column"
>
> The colon `:` is the critical piece. Say: "Think of `:` as meaning 'all'. `data[:, 1]` = all rows, column 1." Then refer to the summary table below. This syntax will come back constantly in Chapter 11 for matrix operations.

In [ ]:
# Experiment data: rows = trials, columns = [Temp(K), Pressure(atm), Conversion]
data = np.array([
    [300, 1.5, 0.92],
    [350, 2.1, 0.85],
    [400, 3.0, 0.78],
    [450, 4.2, 0.70]
 ])
#        0.   1.    2
#  0   [300, 1.5, 0.92],
#  1   [350, 2.1, 0.85],
#  2   [400, 3.0, 0.78],
#  3   [450, 4.2, 0.70]
print("Single element [1, 2]:", data[1, 2])    # Row 1, Col 2 → 0.85
print("Entire row 0:        ", data[0, :])     # [300, 1.5, 0.92]
print("Entire column 1:     ", data[:, 1])     # [1.5, 2.1, 3.0, 4.2]
print("Sub-array [0:2, 1:]:\n", data[0:2, 1:]) # First 2 rows, last 2 columns

Single element [1, 2]: 0.85
Entire row 0:         [300.     1.5    0.92]
Entire column 1:      [1.5 2.1 3.  4.2]
Sub-array [0:2, 1:]:
 [[1.5  0.92]
 [2.1  0.85]]


**Key syntax for 2D indexing:**

| Syntax | Meaning |
|--------|---------|
| `arr[i, j]` | Single element at row `i`, column `j` |
| `arr[i, :]` | Entire row `i` |
| `arr[:, j]` | Entire column `j` |
| `arr[a:b, c:d]` | Sub-array: rows `a` to `b-1`, columns `c` to `d-1` |

(10.3)=
## 10.3 Array Operations

> **Instructor Note:** Transition: "We can create arrays and pull values out of them. Now let's do math." This section is where students see the real power of NumPy. The word "vectorization" will be new to most — define it simply: "applying an operation to every element at once, without writing a loop."

(10.3.1)=
### 10.3.1 Element-wise Arithmetic

Arithmetic operators work **element-by-element** on NumPy arrays. This is called **vectorization** — no loops needed.

> **Instructor Note:** Run the code cell. Emphasize: `a * b` is NOT matrix multiplication — it's element-wise. "Element 0 of `a` times element 0 of `b`, element 1 times element 1, and so on." This distinction will matter in Chapter 11 when they learn `np.dot` and `@` for actual matrix multiplication. Then show the comparison markdown below — the 4-line loop vs the 1-line NumPy. Ask: "Which would you rather write? Which is easier to read? Which is faster?"

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b =", a + b)     # [11, 22, 33, 44]
print("a - b =", a - b)     # [-9, -18, -27, -36]
print("a * b =", a * b)     # [10, 40, 90, 160]
print("b / a =", b / a)     # [10., 10., 10., 10.]
print("a ** 2 =", a ** 2)   # [1, 4, 9, 16]

a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
b / a = [10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16]


Compare this to achieving the same result with a Python list — you'd need a loop:

```python
# With lists (slow, verbose)
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])

# With NumPy (fast, clean)
result = a + b
```

(10.3.2)=
### 10.3.2 Broadcasting

**Broadcasting** is NumPy's way of handling operations between arrays of different shapes. The most common case: an operation between an array and a scalar.

> **Instructor Note:** Students will use broadcasting constantly without realizing it has a name. The two examples here are perfect — unit conversion is something every engineer does. Run the cell and say: "When you write `temps_C + 273.15`, NumPy 'broadcasts' the scalar 273.15 to match the shape of the array, then adds element-wise. You don't need a loop." Keep it to scalar-array broadcasting only — more complex broadcasting rules (2D shape matching) are beyond scope here.

In [18]:
# Scalar + Array: the scalar is "broadcast" to every element
temps_C = np.array([25, 50, 75, 100])
temps_K = temps_C + 273.15    # adds 273.15 to every element
print("Celsius: ", temps_C)
print("Kelvin:  ", temps_K)

# Convert pressures from atm to Pa (1 atm = 101325 Pa)
pressures_atm = np.array([1.0, 2.5, 5.0, 10.0])
pressures_Pa = pressures_atm * 101325
print("\nPressures (atm):", pressures_atm)
print("Pressures (Pa): ", pressures_Pa)

Celsius:  [ 25  50  75 100]
Kelvin:   [298.15 323.15 348.15 373.15]

Pressures (atm): [ 1.   2.5  5.  10. ]
Pressures (Pa):  [ 101325.   253312.5  506625.  1013250. ]


(10.3.3)=
### 10.3.3 Useful Array Functions

NumPy provides built-in functions for common calculations. These are faster than writing your own loops.

> **Instructor Note:** Run the cell. The key ones to highlight: `np.mean` and `np.std` (they'll need these for lab reports with error bars), and `np.argmin`/`np.argmax` (returns the *index*, not the value — a common confusion). Ask: "What's the difference between `np.max(measurements)` and `np.argmax(measurements)`?" (4.6 vs 3). Mention that you can also call these as methods: `measurements.mean()` is the same as `np.mean(measurements)`.

In [19]:
measurements = np.array([4.52, 4.48, 4.55, 4.60, 4.50, 4.53])

print("Sum:  ", np.sum(measurements))
print("Mean: ", np.mean(measurements))
print("Std:  ", np.std(measurements))
print("Min:  ", np.min(measurements))
print("Max:  ", np.max(measurements))
print("Argmin (index of min):", np.argmin(measurements))
print("Argmax (index of max):", np.argmax(measurements))

Sum:   27.18
Mean:  4.53
Std:   0.03829708431025333
Min:   4.48
Max:   4.6
Argmin (index of min): 1
Argmax (index of max): 3


(10.3.4)=
### 10.3.4 The `axis` Argument

For 2D arrays, you can apply functions along a specific axis:
- `axis=0` → operate **down each column** (across rows)
- `axis=1` → operate **across each row** (across columns)

Think of it as: the axis you specify is the one that **collapses**.

> **Instructor Note:** This is the trickiest concept in the chapter — spend extra time here. Draw the 3×4 grid on the board. Then physically gesture: "axis=0 collapses the rows — we squish the 3 rows into 1 row, giving us 4 column averages. axis=1 collapses the columns — we squish the 4 columns into 1 column, giving us 3 row averages." The mnemonic "the axis you specify is the one that disappears" helps. Run the cell and verify the output matches the board drawing. Ask: "If `data.shape` is `(3, 4)`, what shape is `np.mean(data, axis=0)`?" → `(4,)`. "And `axis=1`?" → `(3,)`. If students are still confused, give the physical analogy: "axis=0 is like averaging across all experiments at each time point; axis=1 is like averaging across all time points for each experiment."

In [ ]:
# 3 experiments, each measuring 4 temperatures (K)
data = np.array([
    [305, 310, 315, 320],  # Experiment 1
    [302, 308, 312, 318],  # Experiment 2
    [307, 311, 316, 322],  # Experiment 3
])

print("Data shape:", data.shape)  # (3, 4)
print("Data:\n", data)

# Mean across experiments (down columns) — average temp at each time point
print("\nMean along axis=0 (column means):", np.mean(data, axis=0))

# Mean across time points (across rows) — average temp per experiment
print("Mean along axis=1 (row means):   ", np.mean(data, axis=1))

# Overall mean
print("Overall mean:                    ", np.mean(data))

(10.3.5)=
### 10.3.5 Mathematical Functions

NumPy includes all common math functions that work element-wise on arrays:

> **Instructor Note:** Quick demo — run the cell and move on. The main point: "Use `np.sin`, `np.exp`, `np.log`, etc. instead of `math.sin`, `math.exp`. The `math` module only works on single numbers; NumPy functions work on entire arrays at once." Point out `np.log` is the natural log (ln), not log base 10 — use `np.log10` for that.

In [20]:
x = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("sin(x):", np.sin(x))
print("cos(x):", np.cos(x))
print("exp(x):", np.exp(x))
print("log(x):", np.log(np.array([1, np.e, np.e**2])))  # natural log
print("sqrt(x):", np.sqrt(np.array([4, 9, 16, 25])))

sin(x): [0.         0.5        0.70710678 0.8660254  1.        ]
cos(x): [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
exp(x): [1.         1.68809179 2.19328005 2.84965391 4.81047738]
log(x): [0. 1. 2.]
sqrt(x): [2. 3. 4. 5.]


(10.4)=
## 10.4 Reshaping & Combining Arrays

When preparing data for linear algebra or organizing experimental results, you often need to change the shape of an array or combine multiple arrays together.

> **Instructor Note:** This section is important for Chapter 11 but less intuitive for beginners. Keep it brisk. The three things they need to remember: `reshape` changes dimensions, `.T` transposes, and `vstack`/`hstack` combine arrays. If running low on time, demonstrate reshape and transpose, then mention vstack/hstack briefly and point them to the textbook cell.

(10.4.1)=
### 10.4.1 Reshaping

> **Instructor Note:** Run the cell. The key insight: "reshape doesn't change the data — it rearranges how the same 6 numbers are organized into rows and columns." Point out that the total number of elements must stay the same: you can reshape `(6,)` into `(2,3)` or `(3,2)` or `(6,1)` but NOT `(2,4)` — that would need 8 elements. Try it live if helpful: `a.reshape(2, 4)` will throw a ValueError. Also show `.flatten()` as the inverse — "it unrolls any multi-dimensional array back into 1D."

In [21]:
# reshape: change dimensions without changing data
a = np.array([1, 2, 3, 4, 5, 6])
print("Original (1D):", a, " shape:", a.shape)

# Reshape to 2x3
b = a.reshape(2, 3)
print("Reshaped (2x3):\n", b)

# Reshape to 3x2
c = a.reshape(3, 2)
print("Reshaped (3x2):\n", c)

# Flatten: 2D → 1D
print("Flattened:", b.flatten())

Original (1D): [1 2 3 4 5 6]  shape: (6,)
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]


(10.4.2)=
### 10.4.2 Transpose

The transpose swaps rows and columns. This is essential for linear algebra (Chapter 11).

> **Instructor Note:** Run the cell. Say: "Transpose flips the matrix — rows become columns and columns become rows. A 2×3 becomes a 3×2." The shorthand `.T` is the one they'll use. If any students have taken linear algebra, they'll recognize this. For others, just show that row `[1, 2, 3]` becomes column `[1, 2, 3]`. This will click more in Chapter 11 when they use it for real.

In [22]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original (2x3):\n", A)
print("Transposed (3x2):\n", A.T)

Original (2x3):
 [[1 2 3]
 [4 5 6]]
Transposed (3x2):
 [[1 4]
 [2 5]
 [3 6]]


(10.4.3)=
### 10.4.3 Combining Arrays

> **Instructor Note:** Three functions, one sentence each: "`concatenate` joins 1D arrays end-to-end. `vstack` stacks arrays as new rows (vertical). `hstack` stacks arrays as new columns (horizontal)." Run the cell and point at the outputs. The most practical one is `vstack` — they'll use it when adding new experiment data as a row to an existing table. Don't overexplain — this is reference material they can look up later.

In [23]:
# Concatenate: join arrays along an existing axis
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Concatenate:", np.concatenate([a, b]))  # [1, 2, 3, 4, 5, 6]

# vstack: stack vertically (add rows)
row1 = np.array([300, 1.5, 0.92])
row2 = np.array([350, 2.1, 0.85])
stacked = np.vstack([row1, row2])
print("\nvstack:\n", stacked)

# hstack: stack horizontally (add columns)
col1 = np.array([[1], [2], [3]])
col2 = np.array([[10], [20], [30]])
print("\nhstack:\n", np.hstack([col1, col2]))

Concatenate: [1 2 3 4 5 6]

vstack:
 [[300.     1.5    0.92]
 [350.     2.1    0.85]]

hstack:
 [[ 1 10]
 [ 2 20]
 [ 3 30]]


(10.5)=
## 10.5 Practical Examples

> **Instructor Note:** Transition: "Let's put it all together with two real chemical engineering examples." These examples combine everything from the chapter — array creation, 2D indexing, axis operations, and vectorization. Walk through them more slowly and connect each line back to the concept it uses.

(10.5.1)=
### 10.5.1 Tabulating Experimental Data

Suppose you ran 4 experiments measuring reactor temperature at 5 time points each. You can store all the data in a single 2D array and quickly compute statistics.

> **Instructor Note:** This is the payoff example. Walk through the code line by line:
> - `np.mean(reactor_temps, axis=0)` — "average *across experiments* at each time point" → connects back to 10.3.4
> - `np.mean(reactor_temps, axis=1)` — "average *across time* for each experiment"
> - `reactor_temps[:, -1]` — "extract the last column (final temperatures)" → connects back to 10.2.3
> - `np.argmax(final_temps)` — "which experiment index had the highest?" → connects back to 10.3.3
>
> Ask: "If you had 100 experiments with 50 time points each, would this code change at all?" (No — just the data changes, the operations are the same.) That's the power of NumPy.

In [24]:
# Rows = experiments, Columns = time points (0, 5, 10, 15, 20 min)
# Values = reactor temperature (K)
reactor_temps = np.array([
    [298, 315, 340, 358, 370],  # Experiment 1
    [298, 312, 335, 352, 365],  # Experiment 2
    [298, 318, 345, 362, 375],  # Experiment 3
    [298, 310, 332, 350, 362],  # Experiment 4
])

time_points = np.array([0, 5, 10, 15, 20])  # minutes

print("Temperature data (K):")
print(reactor_temps)
print(f"\nShape: {reactor_temps.shape} (4 experiments x 5 time points)")

# Average temperature at each time point (across experiments)
avg_per_time = np.mean(reactor_temps, axis=0)
print(f"\nAvg temp at each time point: {avg_per_time}")

# Average temperature per experiment (across time)
avg_per_exp = np.mean(reactor_temps, axis=1)
print(f"Avg temp per experiment:     {avg_per_exp}")

# Standard deviation at each time point
std_per_time = np.std(reactor_temps, axis=0)
print(f"Std dev at each time point:  {std_per_time}")

# Which experiment had the highest final temperature?
final_temps = reactor_temps[:, -1]
best_exp = np.argmax(final_temps)
print(f"\nHighest final temp: Experiment {best_exp + 1} ({final_temps[best_exp]} K)")

Temperature data (K):
[[298 315 340 358 370]
 [298 312 335 352 365]
 [298 318 345 362 375]
 [298 310 332 350 362]]

Shape: (4, 5) (4 experiments x 5 time points)

Avg temp at each time point: [298.   313.75 338.   355.5  368.  ]
Avg temp per experiment:     [336.2 332.4 339.6 330.4]
Std dev at each time point:  [0.         3.03108891 4.94974747 4.76969601 4.94974747]

Highest final temp: Experiment 3 (375 K)


(10.5.2)=
### 10.5.2 Vectorized Ideal Gas Law

Instead of computing PV = nRT one condition at a time with a loop, we can compute pressure for many temperatures at once using vectorized operations.

> **Instructor Note:** This connects directly to the ideal gas example from Lab 5. Say: "In the lab, you used a for-loop over temperatures. Watch this — one line of NumPy replaces the entire loop." Point to `pressures = n * R * temperatures / V` and explain: `temperatures` is an array of 7 values, so `pressures` automatically becomes an array of 7 results. The for-loop in the print section is only for display — the actual computation is a single vectorized line. This is how professional scientific code looks.

In [25]:
# Ideal gas law: P = nRT/V
R = 8.314          # J/(mol·K)
n = 1.0            # mol
V = 0.0224         # m³ (≈ 22.4 L)

# Compute pressure at many temperatures simultaneously
temperatures = np.arange(200, 501, 50)  # 200 K to 500 K
pressures = n * R * temperatures / V    # vectorized — no loop!

print("T (K)    |  P (Pa)")
print("-" * 25)
for T, P in zip(temperatures, pressures):
    print(f"  {T}     | {P:>10.1f}")

T (K)    |  P (Pa)
-------------------------
  200     |    74232.1
  250     |    92790.2
  300     |   111348.2
  350     |   129906.2
  400     |   148464.3
  450     |   167022.3
  500     |   185580.4


**Key Takeaways:**
- NumPy arrays are the foundation for scientific computing in Python — fast, compact, and vectorized
- Use `np.array()`, `np.zeros()`, `np.ones()`, `np.linspace()`, `np.arange()` to create arrays
- Index 2D arrays with `[row, col]` syntax; use `:` for entire rows or columns
- Arithmetic operators work element-wise — no loops needed
- Use `axis=0` for column-wise and `axis=1` for row-wise operations
- `.reshape()`, `.T`, `np.vstack()`, `np.hstack()` let you restructure arrays

**Coming up in Chapter 11:** These 2D arrays are matrices — and NumPy provides tools for matrix multiplication, solving systems of linear equations, and other linear algebra operations essential for chemical engineering.

> **Instructor Note:** Wrap up with: "Three things to remember from today: (1) arrays do math, lists don't; (2) `[row, col]` with `:` for slicing; (3) `axis=0` collapses rows, `axis=1` collapses columns." Preview Chapter 11: "Next time, we'll use these arrays as matrices and solve systems of equations — like material balances on a reactor network — in one line of code."