# Lab 04: NumPy Arrays and Linear Algebra

## Examples (by instructor)

In this lab, you'll learn to work with NumPy arrays and perform linear algebra operations essential for chemical engineering calculations.

### Example 1: Creating and Manipulating NumPy Arrays

In [ ]:
import numpy as np

# Create a 1D array of concentrations (mol/L)
concentrations = np.array([0.5, 1.0, 1.5, 2.0, 2.5])
print("Concentrations:", concentrations)

# Create a 2D array (matrix) of rate constants at different temperatures
# Rows: different reactions, Columns: different temperatures
rate_constants = np.array([[0.12, 0.25, 0.48], 
                           [0.08, 0.18, 0.35],
                           [0.15, 0.32, 0.62]])
print("\nRate constants (s^-1):")
print(rate_constants)

# Array operations
print("\nArray shape:", concentrations.shape)
print("Matrix shape:", rate_constants.shape)
print("Sum of concentrations:", np.sum(concentrations))
print("Average rate constant:", np.mean(rate_constants))

### Example 2: Array Indexing and Slicing

In [ ]:
# Create an array of temperatures
temps = np.array([300, 320, 340, 360, 380, 400, 420, 440])

# Indexing examples
print("First temperature:", temps[0])
print("Last temperature:", temps[-1])
print("First three temperatures:", temps[0:3])
print("Every other temperature:", temps[::2])

# 2D array slicing
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("\nOriginal matrix:")
print(data)
print("\nFirst two rows:", data[0:2])
print("Last two columns:", data[:, 2:4])

### Example 3: Vector Operations (Dot and Cross Products)

In [ ]:
# Define two velocity vectors (m/s)
v1 = np.array([3, 6, 9])
v2 = np.array([2, 4, 8])

# Dot product: v1 · v2
dot_product = np.dot(v1, v2)
print(f"v1 = {v1}")
print(f"v2 = {v2}")
print(f"\nDot product (v1 · v2) = {dot_product}")

# Cross product: v1 × v2
cross_product = np.cross(v1, v2)
print(f"Cross product (v1 × v2) = {cross_product}")

# Verify dot product manually
manual_dot = v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2]
print(f"\nManual dot product calculation: {manual_dot}")

### Example 4: Matrix Operations

In [ ]:
# Define two matrices
A = np.array([[2, 3], 
              [4, 1]])

B = np.array([[1, 5], 
              [3, 2]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Matrix multiplication: AB
AB = np.matmul(A, B)
print("\nA × B =")
print(AB)

# Matrix multiplication: BA
BA = np.matmul(B, A)
print("\nB × A =")
print(BA)

print("\nAre AB and BA equal?", np.array_equal(AB, BA))

---

## Practice Problems (by students)

### Problem 1: Dot and Cross Products

Compute analytically the dot and cross products for the two vectors: **a** = (3, 5, 7) and **b** = (4, 6, 3). Use the following definitions:

$$
\mathbf{a} \cdot \mathbf{b} = a_1b_1 + a_2b_2 + a_3b_3
$$

$$
\mathbf{a} \times \mathbf{b} = \det\begin{pmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3
\end{pmatrix}
$$

Check the results in Python. Use `np.dot()` and `np.cross()`.

In [ ]:
# Your solution here


### Problem 2: Array Indexing and Slicing

Having `arr = np.array([6, 12, 18, 24, 30, 36, 42, 48])`, print the following results using indexing/slicing operations:

a) `[6 12 18]`

b) `[36 42 48]`

c) `[6 18 30 42]`

d) `[12 24 36 48]`

e) `[6 24 42]`

In [ ]:
# Your solution here


### Problem 3: Matrix Slicing

Having matrix `m = np.array([[2, 3, 4], [12, 24, 36], [120, 240, 360]])`, print the following results:

a) 
```
[[  2   4]
 [120 360]]
```

b) 
```
[[ 2  3]
 [12 24]]
```

c) 
```
[[ 3  4]
 [24 36]]
```

d) 
```
[[  3   4]
 [ 24  36]
 [240 360]]
```

In [ ]:
# Your solution here


### Problem 4: Matrix Multiplication

Define two matrices and multiply them in two ways: AB and BA. Are the results the same or different? Check in Python.

$$
A = \begin{bmatrix} 2 & 3 \\ 4 & 5 \end{bmatrix}, \quad
B = \begin{bmatrix} 3 & 0 \\ 2 & 4 \end{bmatrix}
$$

In [ ]:
# Your solution here


### Problem 5: Matrix Inverse

Define matrix `M = np.array([[2, 3], [4, 5]])`. Find its inverse M⁻¹ and check that MM⁻¹ = M⁻¹M = I (identity matrix). Check this in Python.

**Hint:** Use `np.linalg.inv()` to find the inverse matrix.

In [ ]:
# Your solution here


### Problem 6: Determinant Calculation

Compute the determinant of the following matrix both analytically and in Python:

$$
\begin{bmatrix}
3 & -2 & 1 \\
4 & 0 & -2 \\
2 & 5 & 6
\end{bmatrix}
$$

**Hint:** Use `np.linalg.det()` to compute the determinant in Python.

In [ ]:
# Your solution here


### Problem 7: Solving System of Linear Equations

Solve the following system of linear equations using Cramer's rule, and then check the result in Python (using `np.linalg.solve(A, b)`):

$$
\begin{align}
2x + 3y + 4z &= 6 \\
4x + 2y - 3z &= 8 \\
-2x + 5y + 8z &= -4
\end{align}
$$

**Note:** For `np.linalg.solve()`, the coefficient matrix A should contain the coefficients of x, y, z, and the vector b should contain the right-hand side values.

In [ ]:
# Your solution here


### Problem 8: Balancing Chemical Equations using Linear Algebra

Use the linear algebra approach to balance the following redox reaction in aqueous solution. To this end, write the problem in matrix form and employ `np.linalg.solve(A, b)` method in Python. Print the found coefficients as integers.

$$
HNO_2 + H^+ + Cr_2O_7^{2-} \rightarrow NO_3^- + Cr^{3+} + H_2O
$$

**Approach:**
1. Assign coefficients: a·HNO₂ + b·H⁺ + c·Cr₂O₇²⁻ → d·NO₃⁻ + e·Cr³⁺ + f·H₂O
2. Write balance equations for each element (H, N, O, Cr) and charge
3. Set one coefficient (e.g., a=1) to make the system solvable
4. Solve for the remaining coefficients
5. Scale to get integer coefficients

In [ ]:
# Your solution here


### Problem 9: Material Balance on a Mixing Tank

A mixing tank receives three inlet streams with the following compositions and flow rates:

| Stream | Flow Rate (kg/h) | Water (wt%) | Ethanol (wt%) | Acetone (wt%) |
|--------|------------------|-------------|---------------|---------------|
| 1      | F₁               | 60          | 30            | 10            |
| 2      | F₂               | 40          | 20            | 40            |
| 3      | F₃               | 30          | 50            | 20            |

The outlet stream has the following specifications:
- Total flow rate: 1000 kg/h
- Water content: 45 wt%
- Ethanol content: 35 wt%

**Tasks:**

a) Set up the material balance equations:
   - Total mass balance: F₁ + F₂ + F₃ = 1000
   - Water balance: 0.60·F₁ + 0.40·F₂ + 0.30·F₃ = 0.45·1000
   - Ethanol balance: 0.30·F₁ + 0.20·F₂ + 0.50·F₃ = 0.35·1000

b) Express this as a matrix equation Ax = b

c) Solve for F₁, F₂, and F₃ using `np.linalg.solve()`

d) Verify that the acetone balance is satisfied

e) Check that all flow rates are positive (physically meaningful)

In [1]:
# Your solution here
import numpy as np

# Problem 9: Material Balance on a Mixing Tank

# Step a) & b) Set up the coefficient matrix A and constant vector b
# Equations:
# F1 + F2 + F3 = 1000              (total mass balance)
# 0.60*F1 + 0.40*F2 + 0.30*F3 = 450  (water balance)
# 0.30*F1 + 0.20*F2 + 0.50*F3 = 350  (ethanol balance)

A = np.array([[1.0,  1.0,  1.0],    # Total mass balance coefficients
              [0.60, 0.40, 0.30],    # Water balance coefficients
              [0.30, 0.20, 0.50]])   # Ethanol balance coefficients

b = np.array([1000, 450, 350])      # Right-hand side values

print("Coefficient matrix A:")
print(A)
print("\nConstant vector b:")
print(b)

# Step c) Solve for F1, F2, F3 using np.linalg.solve()
flow_rates = np.linalg.solve(A, b)
F1, F2, F3 = flow_rates

print("\n" + "="*50)
print("SOLUTION:")
print("="*50)
print(f"F1 (Stream 1) = {F1:.2f} kg/h")
print(f"F2 (Stream 2) = {F2:.2f} kg/h")
print(f"F3 (Stream 3) = {F3:.2f} kg/h")

# Step d) Verify that the acetone balance is satisfied
# Acetone balance: 0.10*F1 + 0.40*F2 + 0.20*F3 = acetone_out
acetone_in = 0.10*F1 + 0.40*F2 + 0.20*F3
acetone_out_expected = (1.0 - 0.45 - 0.35) * 1000  # Remaining wt% = 20%

print("\n" + "="*50)
print("VERIFICATION:")
print("="*50)
print(f"Acetone in inlet streams: {acetone_in:.2f} kg/h")
print(f"Acetone in outlet (expected): {acetone_out_expected:.2f} kg/h")
print(f"Acetone balance satisfied: {np.isclose(acetone_in, acetone_out_expected)}")

# Additional verification: check all material balances
total_mass = F1 + F2 + F3
water_in = 0.60*F1 + 0.40*F2 + 0.30*F3
ethanol_in = 0.30*F1 + 0.20*F2 + 0.50*F3

print(f"\nTotal mass balance: {total_mass:.2f} kg/h (target: 1000)")
print(f"Water balance: {water_in:.2f} kg/h (target: 450)")
print(f"Ethanol balance: {ethanol_in:.2f} kg/h (target: 350)")

# Step e) Check that all flow rates are positive (physically meaningful)
print("\n" + "="*50)
print("PHYSICAL FEASIBILITY CHECK:")
print("="*50)
if np.all(flow_rates > 0):
    print("✓ All flow rates are positive - solution is physically meaningful")
    print(f"  F1 > 0: {F1 > 0}")
    print(f"  F2 > 0: {F2 > 0}")
    print(f"  F3 > 0: {F3 > 0}")
else:
    print("✗ Warning: Some flow rates are negative - solution may not be physical")
    for i, F in enumerate(flow_rates, 1):
        if F < 0:
            print(f"  F{i} = {F:.2f} kg/h (NEGATIVE!)")

# Summary table
print("\n" + "="*50)
print("COMPOSITION VERIFICATION:")
print("="*50)
print(f"{'Component':<12} {'Inlet (kg/h)':<15} {'Outlet (kg/h)':<15} {'Match?':<10}")
print("-"*50)
print(f"{'Water':<12} {water_in:<15.2f} {450.0:<15.2f} {np.isclose(water_in, 450)}")
print(f"{'Ethanol':<12} {ethanol_in:<15.2f} {350.0:<15.2f} {np.isclose(ethanol_in, 350)}")
print(f"{'Acetone':<12} {acetone_in:<15.2f} {acetone_out_expected:<15.2f} {np.isclose(acetone_in, acetone_out_expected)}")
print(f"{'TOTAL':<12} {total_mass:<15.2f} {1000.0:<15.2f} {np.isclose(total_mass, 1000)}")

Coefficient matrix A:
[[1.  1.  1. ]
 [0.6 0.4 0.3]
 [0.3 0.2 0.5]]

Constant vector b:
[1000  450  350]

SOLUTION:
F1 (Stream 1) = 428.57 kg/h
F2 (Stream 2) = 214.29 kg/h
F3 (Stream 3) = 357.14 kg/h

VERIFICATION:
Acetone in inlet streams: 200.00 kg/h
Acetone in outlet (expected): 200.00 kg/h
Acetone balance satisfied: True

Total mass balance: 1000.00 kg/h (target: 1000)
Water balance: 450.00 kg/h (target: 450)
Ethanol balance: 350.00 kg/h (target: 350)

PHYSICAL FEASIBILITY CHECK:
✓ All flow rates are positive - solution is physically meaningful
  F1 > 0: True
  F2 > 0: True
  F3 > 0: True

COMPOSITION VERIFICATION:
Component    Inlet (kg/h)    Outlet (kg/h)   Match?    
--------------------------------------------------
Water        450.00          450.00          True
Ethanol      350.00          350.00          True
Acetone      200.00          200.00          True
TOTAL        1000.00         1000.00         True
